apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk037-backend
  namespace: class-2
spec:
  selector:
    matchLabels:
      app: sk037-backend
  template:
    metadata:
      labels:
        app: sk037-backend
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: backend
          image: __BE_IMAGE__
          env:
            - name: DB_HOST
              value: "sk037-db"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sk037-backend
  namespace: class-2
spec:
  selector:
    app: sk037-backend
  ports:
    - port: 8000
      targetPort: 8000