apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sk037-ingress
  namespace: class-2
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          # 1. 백엔드 설정
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sk037-backend
                port:
                  number: 8000
                  
          # 2. 프론트엔드 설정
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sk037-frontend
                port:
                  number: 8080
